//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string Resume { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Prof_Id { get; set; }
    
        public virtual Prof_Details Prof_Details { get; set; }
    }
}
